package gesut.gml;

import gesut.repository.dao.*;

public enum GmlObjectTypes {
    BUDOWLAPODZIEMNA,
    KORYTARZPRZESYLOWY,
    OBIEKTKARTO,
    OBUDOWAPRZEWODU,
    PRZEWODBENZYNOWY,
    PRZEWODCIEPLOWNICZY,
    PRZEWODELEKTROENERGETYCZNY,
    PRZEWODGAZOWY,
    PRZEWODINNY,
    PRZEWODKANALIZACYJNY,
    PRZEWODNAFTOWY,
    PRZEWODNIEZIDENTYFIKOWANY,
    PRZEWODTELEKOMUNIKACYJNY,
    PRZEWODWODOCIAGOWY,
    PUNKTOOKRESLONEJWYSOKOSCI,
    SLUPIMASZT,
    URZADZENIETECHNICZNEZWIAZANEZSIECIA,
    BRAKOBIEKTU;

}
